services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "52001:8000"
    volumes:
      - ./data:/app/data:ro
      - ./fastapi_server/mlruns:/app/mlruns
    environment:
      - DATA_PATH=/app/data/Flights.csv